[test] Adapt new error message and new behavior
- New error message "Standard input is not a terminal" should be ignored.
- nano changed its behavior to produce error messages AFTER program exited.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,6 +35,9 @@ jobs:
         run: |
           mkdir -p ~/.nano/
           cp -al *.nanorc ~/.nano/
-          TERM=xterm timeout 1s nano --rcfile ./nanorc >/dev/null 2>error.txt || true
-          grep -v -e "Received SIGHUP or SIGTERM" -e "Too many errors from stdin" error.txt && false
+          echo "" | TERM=xterm timeout 1s nano --rcfile ./nanorc >/dev/null 2>error.txt || true
+          if grep -v -e "Received SIGHUP or SIGTERM" -e "Too many errors from stdin" \
+                    -e "Standard input is not a terminal" error.txt; then
+            exit 1
+          fi
           echo "All seems good!"
